name: CI

on:
  push:
    branches: [ $default-branch ]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20.5.0
