name: CI

on:
  push:
    branches: [ main ]
   
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20.5.0

      - name: Instalação do Mocha e dos pacotes para teste
        run:
          cd src;
          npm install -g mocha;
          npm install

      - name: Execução do teste
        run: mocha src/test/convert.js

      - name: Autenticação no Docker Hub
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
        
      - name: Construção da imagem Docker
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            rfogaca/aula-convercao-temperatura:v1
            rfogaca/aula-convercao-temperatura:latest
